// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgIAWXWBXAy6bvk5iA3JnyIgVg6UNwPQ',
    appId: '1:546902102564:web:76c625fe81134c499bfeb1',
    messagingSenderId: '546902102564',
    projectId: 'dial-vault-17004',
    authDomain: 'dial-vault-17004.firebaseapp.com',
    databaseURL: 'https://dial-vault-17004-default-rtdb.firebaseio.com',
    storageBucket: 'dial-vault-17004.appspot.com',
    measurementId: 'G-BFQNVNNSR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGyIs0wafbkYzIT78z3LJhwtyv39iFhak',
    appId: '1:546902102564:android:d1f4948463126a979bfeb1',
    messagingSenderId: '546902102564',
    projectId: 'dial-vault-17004',
    databaseURL: 'https://dial-vault-17004-default-rtdb.firebaseio.com',
    storageBucket: 'dial-vault-17004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8qHXx6XIE7UTHwBnric95nYNmG1pp74U',
    appId: '1:546902102564:ios:ae0fbe3a66c78b549bfeb1',
    messagingSenderId: '546902102564',
    projectId: 'dial-vault-17004',
    databaseURL: 'https://dial-vault-17004-default-rtdb.firebaseio.com',
    storageBucket: 'dial-vault-17004.appspot.com',
    androidClientId: '546902102564-ajm50sa0qj2j7kmtacq6gkkq8hmaulik.apps.googleusercontent.com',
    iosClientId: '546902102564-9j9i193mmsuq1ebfm4igur9e95f93a9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.valtSecurityAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8qHXx6XIE7UTHwBnric95nYNmG1pp74U',
    appId: '1:546902102564:ios:ae0fbe3a66c78b549bfeb1',
    messagingSenderId: '546902102564',
    projectId: 'dial-vault-17004',
    databaseURL: 'https://dial-vault-17004-default-rtdb.firebaseio.com',
    storageBucket: 'dial-vault-17004.appspot.com',
    androidClientId: '546902102564-ajm50sa0qj2j7kmtacq6gkkq8hmaulik.apps.googleusercontent.com',
    iosClientId: '546902102564-9j9i193mmsuq1ebfm4igur9e95f93a9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.valtSecurityAdminPanel',
  );
}
